---
name: Build Game

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
      
      - name: Run Tests
        run: go test ./... -v

  build:
    name: Build Binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows]
        goarch: [amd64]
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
      
      - name: Build Application
        run: |
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o beesinthetrap-${{ matrix.goos }}-${{ matrix.goarch }} ./cmd/beesinthetrap
      
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: beesinthetrap-${{ matrix.goos }}-${{ matrix.goarch }}
          path: beesinthetrap-${{ matrix.goos }}-${{ matrix.goarch }}

  # release:
  #   name: Create GitHub Release
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout Code
  #       uses: actions/checkout@v4
      
  #     - name: Download Build Artifacts
  #       uses: actions/download-artifact@v4
      
  #     - name: Create GitHub Release
  #       uses: softprops/action-gh-release@v2
  #       with:
  #         tag_name: ${{ github.ref_name }}
  #         files: "beesinthetrap-*"
